# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RzqD7GmzxPYJ+7w3fNlL4lLAB0ott8NbCjfEoUUR23cf2X6XKkylgGJLq943TwOuU88TXlg1Og9c0hr4AvfdBzXHqoFUHlnbpRf+dMPtUHzB86gcer036NV6lqnIJvAsxcigfHuWiCq7vSZVMGnfTiMpZ8PlpjiwPFweOWqUzUZaJuH9Vuuy85904EIjHuFMYJ7A5wrykIU2nvIh+Bcya42sRwNETMt+FnOZ/ruNWs1ljqc/wxJV/oGAVPHVOyY64axrVwMxPIrHLu9hIfFCvkzP8sbi+pCcLzUw8cBiib8qox2rNWPhlXclzQZOjqZW/Yu1D0nohqPdbaudtK1OrhPSJfby6qqJMUARDA4isXEBeu2m4h/hShBbb0m4gkoCIPfmfCpb6Cym0faMmpPwvtBPmpfeMbKpvWKY1xPjdMpEl2YyVez5WIfRo9meFMeDo+ROzDvH1sIOCy7/XFMoIMMXyvWWIkQbrnwP/pV4IkjY1/ny/IrROIRIFgkomVO/ASw3Ci3YURqNh1epcej9I3oMwMWKD1RlXP483AYO/wrpkBD24hw/e+iAy7nBcMKWSWQDnW9J8IZz5NwuvyBfu8gQCQPg0LXrtgeaCT+tneljGsLciXMozsiiaER2BnC71QzdgiXhpHlAZyq3mV5FyaubrCK34nZp+fyoJuN/WLc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml