travis:
  secure:
    BINSTAR_TOKEN: axl184Tm++BbfPrxPnFvFKFpGICEBxtjK5e0T/NAfuOEs0s7ImkwNxRv4trzuDERjsu6hsQdoHswbIxpc4rkaGRZkVlVKS7poLlt9e2VLiPFBu5r726v+yHCvT/f2M18tNzFyrhXYr6CtLsHn0WEJvoGsV69SWxrDC7xOY4pqi2D7apkdxM04z2sMznY0bXTM7SbP1Rm+MBa5isv2/ZnsQ3cW/2tlp9hqBA+i9PwFSxGt1mPIrd/nBo/rG0L4yLJc8qTba4IMweAQrV4FJU8CNc7kEC2uVwywJCUXwPPRB/uWH7U4kuL+A3gUxwtg1FIltjn83iKEKg76aEIZF7xwgspZL4NftU/9nfIWYr95iqwNgwlmyOzKQM5ob+ADdLY27fqAfj9qJpk0QibRkoeIe9VXZa3Be9asp0xujYIJs6wApsGIHQxJrsaM2Q+enb0cX9nspkUQQ2jbkLpa23aTLkMmWSuNPhdZ83N0e+zHAPP1NhcGThx4sCRpxJZ79FNbvt9exhWUfntYvKtT738g/3Th2YhW/IvNygJZse7zFgYsLYkYL6ww/iJA/F91pSIcK17sv153V7RJN50TcGw/EK7xlup0Ta5EpnI3dJd08WG8jKifpuCIXg6L6Mlw5dbpKJxAuAI2wKGBiJAWtyb+1sJUyQ3c8Y8EVGPphLeBuo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: false
